name: DCS
favicon: null
layout_spectrum: 0.07025361922569573
typography_spectrum: 0.9579164579045027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.023393716430291533
  lightness: 0.7040581943001598
  saturation: 0.2179043951909989
  rhythmicContrast: 0.80092518706806
purpose: []
